### PR TITLE
2253 handle url encoded

### LINKED ISSUE #2253: HttpUrlProxyAdapter chokes on already encoded URLs
I believe [this change](https://github.com/thoughtbot/paperclip/commit/8ab50b9194185eec8453283f195b4e4c2def3fc7#diff-968b30a7d52083bb1326639b64926d85) has caused a regression in URL handling in HttpUrlProxyAdapter. It's currently preventing you from attaching files that have URLs that are **already** encoded.

Here's an example link to an image file on GitHub: 

```
https://cloud.githubusercontent.com/assets/769083/16889697/434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png
```

Here's a different way to write that link (with two encodeded forward slashes): 

```
https://cloud.githubusercontent.com/assets/769083%2F16889697%2F434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png
```

And here's a reproduction script:

``` ruby
require "active_support/all"
require "paperclip"

RUBY_VERSION
#=> "2.3.1"

Paperclip::VERSION 
#=> 5.0.0

# Regular URL
Paperclip::HttpUrlProxyAdapter.new("https://cloud.githubusercontent.com/assets/769083/16889697/434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png")
#=> Paperclip::HttpUrlProxyAdapter: 434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png

# Encoded slashes
Kernel.open("https://cloud.githubusercontent.com/assets/769083%2F16889697%2F434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png").length
#=> 140806

# Encoded slashes
Paperclip::HttpUrlProxyAdapter.new("https://cloud.githubusercontent.com/assets/769083%2F16889697%2F434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png")
# => OpenURI::HTTPError: 403 Forbidden
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:359:in `open_http'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:717:in `open'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:31:in `open'
# => from /Users/You/.gem/ruby/2.3.1/gems/paperclip-5.0.0/lib/paperclip/io_adapters/uri_adapter.rb:19:in `download_content'
# => from /Users/You/.gem/ruby/2.3.1/gems/paperclip-5.0.0/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'
# => from /Users/You/.gem/ruby/2.3.1/gems/paperclip-5.0.0/lib/paperclip/io_adapters/http_url_proxy_adapter.rb:7:in `initialize'
# => from (irb):5:in `new'
# => from (irb):5
# => from /Users/You/.rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

### PR DESCRIPTION
**Pull request by ivanoblomov**
Closes #2253.

Allow `HttpUrlProxyAdapter` to handle already-escaped targets by calling `URI.escape` only when necessary (since the latter *isn't* idempotent).

### CODE REVIEW

File: lib/paperclip/io_adapters/http_url_proxy_adapter.rb [hunk 1]
```diff
@@ -4,9 +4,9 @@ class HttpUrlProxyAdapter < UriAdapter
     REGEXP = /\Ahttps?:\/\//
 
     def initialize(target, options = {})
-      super(URI(URI.escape(target)), options)
+      escaped = URI.escape(target)
+      super(URI(target == URI.unescape(target) ? escaped : target), options)
```
Comment (januszm) [inline lib/paperclip/io_adapters/http_url_proxy_adapter.rb]: It'd be great to merge this. I was about to create an issue in Paperclip just before I saw this. 

Here's the story, if your URI is already `URI.escape`(d), the current code will return bad, double escaped URI. I use a similar method of testing whether the URI is already escaped or not in one of the production apps.

**Comment by januszm** [comment]
👍
